### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by ForrestPi** [nsarafianos/Garment3DGen#1]
in loop.py

deformed_features = fclip.encode_image_tensors(train_render)
AttributeError: 'FashionCLIP' object has no attribute 'encode_image_tensors'

**Comment by nsarafianos** [comment]
Hi @ForrestPi 

Good catch. I had made some changes in the fclip python file. I updated the codebase to include it directly under packages along with the function that threw the error for you. 

Hopefully it works for you now :)

**Comment by ForrestPi** [comment]
@nsarafianos thanks
