### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by githubnameoo** [nsarafianos/Garment3DGen#10]
When running main.py epoch 1800 batchsize 24, it takes more than120 minutes and the transformed geometry is not ideal. How can I solve this problem?

**Comment by nsarafianos** [comment]
Hi @githubnameoo and thank you for trying our work. 

Can you provide some additional details if possible? Eg (how many vertices does your geometry have, what GPU are you using etc). 

It should not take that long and you should have a very good idea if it's going to work within a few minutes.
