### ISSUE TITLE
problems about grad = igl.grad(v, f), returns all zeros

### ISSUE THREAD

**Issue by dlg-dlg** [nsarafianos/Garment3DGen#11]
When I run python main.py using example_config.yml, it can't save new_rhs.npz. After debuging, I found that it's because the gradient computed in line 389 of poisson_system_matrices_from_mesh,grad = igl.grad(v, f), returns all zeros. I installed libigl using python -m pip install libigl==2.4.1. I don't know why this is happening. Could you please provide some help?

**Comment by nsarafianos** [comment]
Hi @dlg-dlg and apologies for the delayed response. I did not encounter this problem before. Your libigl version and installation via pip seems fine to me. If you're still encountering this issue please follow up here (or send me an email) and I'm happy to take a look! Another thing to test is if you can run TextDeformer (just the [off-the-shelf code](https://github.com/threedle/TextDeformer) which uses libigl and if this also is not working I'd suggest looking into the libigl installation a little more. )
