### ISSUE TITLE
Textured Garment Generation?

### ISSUE THREAD

**Issue by yitongdeng** [nsarafianos/Garment3DGen#12]
Hi! I am very interested in this great project. So far, I am able to set up on my computer and run the default, shirt-to-jacket example (as shown in attached gif). However, I am not seeing an easy way to generate textured garments using image or text prompts. I wonder if I am missing the proper instruction to do so or if the texturing code will be released in the future? Thank you!

![1](https://github.com/user-attachments/assets/8877f2fb-c5c9-4586-9dbd-b5e18706dc1b)

**Comment by xinyuzhang915** [comment]
That's the same video that I run main.py's final output and was wondering if your problem was solved?

**Comment by nsarafianos** [comment]
Hi @yitongdeng  and @xinyuzhang915 and apologies for the delayed response. Unfortunately we cannot share the texture estimation code. However there's a plethora of really good public works (TEXTure, Text2tex) one could use.  Btw I was playing with [this one](https://flashtex.github.io/) last week. I'd encourage you to plug any of these works to our method and should work pretty well. Happy to answer any questions you might have!
