### ISSUE TITLE
Could you provide the reconstructed OBJ file for jacket_sdf_new.obj? I rebuilt it on my computer, but the result is not ideal. I’m not sure if this unsatisfactory result is related to my hardware or environment

### ISSUE THREAD

**Issue by TanJinxia** [nsarafianos/Garment3DGen#13]
Could you provide the reconstructed OBJ file for jacket_sdf_new.obj? I rebuilt it on my computer, but the result is not ideal. I’m not sure if this unsatisfactory result is related to my hardware or environment

**Comment by nsarafianos** [comment]
Hi @TanJinxia and thank you for reaching out. Apologies for the delayed response. Can you please send me an email (you can find it [here](https://nsarafianos.github.io/)) and I'm happy to help.
