### ISSUE TITLE
About simulation code

### ISSUE THREAD

**Issue by MontaEllis** [nsarafianos/Garment3DGen#3]
Nice work! Can you opensource some simulation applications?

**Comment by nsarafianos** [comment]
Hi @MontaEllis  and thank you for reaching out. Unfortunately the geometry aspect of this work is all we are allowed to share externally. Neither the texture aspect of it (which at least one can find several great works out there) nor the simulation can be shared. If you have something specific you'd like to test please drop me an email (my info is [here](https://nsarafianos.github.io/)) and I'll do my best to get back to you with some simulation results :)
