### ISSUE TITLE
Questions about texture estimation

### ISSUE THREAD

**Issue by CiciBEASTARS** [nsarafianos/Garment3DGen#4]
Nice work!
I have some questions about the texture estimation stage: I find the textures generated in the paper to be very view-consistent and detailed, and I noticed that you mentioned conducting depth-aware inpainting to get locally consistent textures. Could you kindly specify which inpainting model you exactly used? Are the initial textures already view-consistent, or do they become consistent after the texture enhancement stage? I've tried a few inpainting methods but couldn't achieve seamless textures.
Thanks a lot!

**Comment by nsarafianos** [comment]
Hi @CiciBEASTARS and thank you for your kind words! I'm copying the responses of my colleague who was responsible for this part. If these responses are not answering your questions fully please send me an email (you can find it [here](https://nsarafianos.github.io/)) and I'd be more than happy to bring you in touch with them. 

1. We use Multi-controlnet with depth and inpainting controls
2. The initial textures are consistent at the beginning, thanks to Wonder3D generating 6 views at once (or any other model you'd like to try that can potentially provide you more views and that are also more multi-view consistent)
3. As a result, the enhancement stage just refine the textures on top of the initial one

**Comment by CiciBEASTARS** [comment]
Got it! Thanks for your quick reply!
