### ISSUE TITLE
Can you please provide the RGB image corresponding to the sample provided in meshes_target?

### ISSUE THREAD

**Issue by NagabhushanSN24** [nsarafianos/Garment3DGen#5]
Hi,

Can you please provide the RGB image corresponding to the `jacket_sdf_new.obj` sample provided in `meshes_target`?

**Comment by nsarafianos** [comment]
Hi @NagabhushanSN24 

Please try this [link](https://www.montbell.us/products/prod_img/zoom/z_2301368_bric.jpg). Should you need additional images please let me know and I can upload them to a folder or something. 

Have a nice day
