### ISSUE TITLE
Can I feed input image with person wearing the garment?

### ISSUE THREAD

**Issue by NagabhushanSN24** [nsarafianos/Garment3DGen#6]
Hi,

In the teaser figure of the paper, you show the input as a person wearing the garment. But the subsequent figures in the paper contain only the image of the garment as input. Is it possible to feed an image of a person wearing the garment?

I tried feeding one such example and the final mesh tried to model the person as well.

**Comment by nsarafianos** [comment]
Great question. If you'd like to do that you will need to segment the cloth out of the human and keep only that (using SAM or your model of choice) and then pass only that. 

In addition, when providing a clothed human image it's usually preferable to not have occlusions (eg hand in front of the torso etc, the ideal case is something like a T-pose or A-pose) such that the garment can be fully-visible.

**Comment by NagabhushanSN24** [comment]
Understood, thanks!
