### ISSUE TITLE
doublehong666@163.com

### ISSUE THREAD

**Issue by chaohongguo** [nsarafianos/Garment3DGen#7]
when i run main.py,some problem occur,do you know why?
 ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by 
/XXX/lib/python3.8/site-packages/pymeshlab/pmeshlab.cpython-38-x86_64-linux-gnu.so)

**Comment by nsarafianos** [comment]
Hi @chaohongguo 

Please check here: https://www.perplexity.ai/search/when-i-run-main-py-some-proble-qM_rAMZDTaeNMSomEIFykg

Feel free to dig into it a little yourself (using Perplexity/ChatGPT or your favorite tool) but the issue described above should be the culprit
