### ISSUE TITLE
About texture used for rendering in mesh deformation stage

### ISSUE THREAD

**Issue by VVingerfly** [nsarafianos/Garment3DGen#8]
Hi，Nikos
Thanks for your great work!
I have a question about the paper. In the mesh deformation stage，you render both the deformed mesh and target mesh to compute image and CLIP losses，I'm wondering where the texture maps of deformed mesh comes from? Or how you generate them in mesh deformation stage?
Looking forward to your reply, Thanks :)

**Comment by nsarafianos** [comment]
Hi @VVingerfly  and thank you for your question. 

So during the deformation stage we do not render any colorful textures (that are generated later) but instead we render both the deformed and the ground-truth meshes using a default shader and as such they all appear gray-ish. You can check here for the 2 material definitions.  

1. loop.py#L186
2. loop.py#L210

**Comment by VVingerfly** [comment]
Got it, thanks for your reply!
